# ~/projects/pyproject.toml
[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "algorithm"         # what you will import
version = "0.0.1"

[tool.setuptools.packages.find]
where = ["algorithm"]      # only package to expose